In [24]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('CV.csv')

# create the scripts to sort dataframe by the salary, age, experience and title (in alphabetical order) 
df = df.sort_values(by=['Salary'])
df = df.sort_values(by=['Age'])
df = df.sort_values(by=['Title'])
df = df.sort_values(by=['Experience Year'])
df = df.sort_values(by=['Experience Month']) 

#create the scripts to calculate minimum, maximum and mean average of the salary of all 
# min_salary = df['Salary'].min()
# max_salary = df['Salary'].max()
# mean_salary = df['Salary'].mean()

# print('Minimum salary: ', min_salary)
# print('Maximum salary: ', max_salary)
# print('Mean average salary: ', mean_salary)

#create the scripts to calculate minimum, maximum and mean average of the salary of each sex, specialization and citizenship. Results must be the dataframe
# df = df.groupby(['Sex', 'Specialization', 'Citizenship'])['Salary'].agg(['min', 'max', 'mean'])

# count_stats = df.groupby(['Citizenship', 'Sex'])['cv'].agg(['count'])
df

,Title,Specialization,Salary,Age,Employment,Work Schedule,Experience Year,Experience Month,Citizenship,Sex
5,DevOps инженер / AWS+terraform+kubernetes / MLOps,"Программист, разработчик",3 000 USD на руки,43 года,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",16 лет,11 месяцев,Казахстан,Мужчина
6,"ML Engineer, Data scientist","Программист, разработчик Аналитик",400 000 KZT на руки,30 лет,полная занятость,полный день,5 лет,1 месяц,Казахстан,Мужчина
13,"Начальник отдела ИТ, менеджер ИТ-проектов, сис...",Директор по информационным технологиям (CIO) С...,NaN,43 года,полная занятость,полный день,20 лет,4 месяца,Казахстан,Мужчина
0,Python Django Developer,"Программист, разработчик",NaN,31 год,"проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...",6 лет,4 месяца,Казахстан,Мужчина
4,Web-разработчик Python/Django,"Программист, разработчик",200 000 KZT на руки,36 лет,"стажировка, частичная занятость, полная занятость","удаленная работа, гибкий график, полный день, ...",14 лет,5 месяцев,Казахстан,Женщина
12,Программист Python,"Программист, разработчик",NaN,22 года,"проектная работа, стажировка, волонтерство, ча...","удаленная работа, гибкий график, полный день",2 года,7 месяцев,Казахстан,Мужчина
8,Python Backend Developer,"Программист, разработчик",NaN,22 года,полная занятость,"удаленная работа, полный день",3 года,7 месяцев,Казахстан,Мужчина
16,Python Backend Developer,"Программист, разработчик",900 000 KZT на руки,27 лет,полная занятость,удаленная работа,5 лет,7 месяцев,Казахстан,Мужчина
15,Python Developer,"Программист, разработчик",NaN,38 лет,"проектная работа, стажировка, частичная занято...","вахтовый метод, удаленная работа, гибкий графи...",13 лет,8 месяцев,Казахстан,Мужчина
3,Программист Python Django,"Программист, разработчик",500 EUR на руки,40 лет,"проектная работа, стажировка, полная занятость","удаленная работа, полный день, вахтовый метод",2 года,8 месяцев,Казахстан,Мужчина
18,Программист,"Программист, разработчик",NaN,28 лет,полная занятость,"полный день, вахтовый метод",4 года,8 месяцев,Казахстан,Мужчина
9,"Web-программист, программист Python","Программист, разработчик",NaN,32 года,"частичная занятость, полная занятость","вахтовый метод, удаленная работа, гибкий графи...",10 лет,9 месяцев,Казахстан,Мужчина
11,Оператор ПК,"Оператор ПК, оператор базы данных",200 000 KZT на руки,18 лет,"стажировка, частичная занятость, проектная раб...","гибкий график, полный день, сменный график, уд...",1 год,9 месяцев,Казахстан,Мужчина
14,Специалист по IT,Системный инженер,20 000 KGS на руки,29 лет,"стажировка, частичная занятость, проектная раб...","гибкий график, полный день, удаленная работа",3 года,9 месяцев,Кыргызстан,Мужчина
1,"Программист Python, Django","Программист, разработчик",500 000 KZT на руки,34 года,полная занятость,"удаленная работа, полный день",11 лет,NaN,Казахстан,Мужчина
7,Backend разработчик,"Программист, разработчик",NaN,21 год,полная занятость,"полный день, удаленная работа",11 месяцев,NaN,Казахстан,Мужчина
19,Software Developer,"Программист, разработчик",NaN,22 года,полная занятость,полный день,2 года,NaN,Казахстан,Мужчина
17,Backend Developer,"Программист, разработчик",NaN,21 год,полная занятость,полный день,3 месяца,NaN,Казахстан,Мужчина
10,Python Junior Developer,"Программист, разработчик",NaN,31 год,полная занятость,"гибкий график, полный день, удаленная работа",NaN,NaN,Казахстан,Мужчина
2,Веб-разработчик Python.Django,"Программист, разработчик",NaN,20 лет,"стажировка, частичная занятость","удаленная работа, гибкий график, сменный график",NaN,NaN,Казахстан,Мужчина